export const tokens = {
  colors: {
    primary: '#1D9E75',
    primaryDark: '#17A564',
    secondary: '#378ADD',
    accent: '#F5A623',
    danger: '#E74C3C',
    neutralBg: '#F5F5F5',
    neutralSurface: '#FFFFFF',
    neutralDark: '#2C3E50',
    neutralMuted: '#6B7280',
    neutralBorder: '#E5E7EB',
    successBg: '#E8F8F2',
    successText: '#1D9E75',
    warningBg: '#FEF5E7',
    warningText: '#B9730D',
    errorBg: '#FDECEA',
    errorText: '#C0392B',
    infoBg: '#EAF2FB',
    infoText: '#2D7DCC',
    teamA: '#F5A623',
    teamB: '#378ADD',
    medalGold: '#F5D130',
    medalSilver: '#C0C0C0',
    medalBronze: '#CD7F32',
    darkBg: '#1A1F2E',
    darkSurface: '#242B3D',
  },
  typography: {
    fontFamily: 'Inter',
    sizes: {
      h1: 24,
      h2: 18,
      h3: 16,
      body: 14,
      caption: 12,
      overline: 10,
    },
    weights: {
      bold: '700',
      semibold: '600',
      regular: '400',
    },
    lineHeights: {
      heading: 1.2,
      body: 1.5,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  radius: {
    sm: 4,
    md: 8,
    lg: 16,
    full: 999,
  },
  shadows: {
    card: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    elevated: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
    },
  },
  transitions: {
    push: 300,
    pop: 250,
    slide: 300,
    sheet: 250,
    fade: 200,
    toast: 200,
  },
  layout: {
    buttonHeight: 48,
    touchTarget: 44,
    bottomNavHeight: 56,
  },
};

export default tokens;